package form.atplist;

import form.tournament.FrmSearchTournament;
import controller.Communication;
import domain.ATPList;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import components.TableModelATPList;

/**
 *
 * @author DELL
 */
public class FrmSearchATPLists extends javax.swing.JDialog {
    
    List<ATPList> atpLists;
    List<ATPList> newATPLists;

    public FrmSearchATPLists(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Search ATP Lists");
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtATPList = new javax.swing.JTextField();
        panelATPLists = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblATPLists = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ATPLists:");

        jLabel2.setText("Insert name of the atp list: ");

        panelATPLists.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblATPLists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblATPLists);

        javax.swing.GroupLayout panelATPListsLayout = new javax.swing.GroupLayout(panelATPLists);
        panelATPLists.setLayout(panelATPListsLayout);
        panelATPListsLayout.setHorizontalGroup(
            panelATPListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelATPListsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelATPListsLayout.setVerticalGroup(
            panelATPListsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelATPListsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtATPList, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelATPLists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtATPList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelATPLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = txtATPList.getText().trim();
        newATPLists = new ArrayList<>();
        
        try {
            atpLists = Communication.getInstance().getAllATPLists();
        } catch (Exception ex) {
            Logger.getLogger(FrmSearchATPLists.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (ATPList a : atpLists) {
            if(a.getName().equalsIgnoreCase(name) || a.getName().toLowerCase().contains(name.toLowerCase()) || a.getName().toUpperCase().contains(name.toUpperCase()) || a.getName().contains(name)) {
                newATPLists.add(a);
            }
        }
        if(newATPLists.isEmpty()) {
           JOptionPane.showMessageDialog(this, "The system cannot find ATP Lists at the given value.", "Search", JOptionPane.ERROR_MESSAGE);
           return; 
        }
        prepareTable(newATPLists);
        btnDetails.setVisible(true);
        JOptionPane.showMessageDialog(this, "The system has found ATP Lists at the given value.", "Search", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        try {
            ATPList atplist = new ATPList();
            atpLists = Communication.getInstance().getAllATPLists();
            String name = (String) (tblATPLists.getModel().getValueAt(tblATPLists.getSelectedRow(), 0));
            for (ATPList a : atpLists) {
                if(a.getName().equals(name)) {
                    atplist = a;
                }
            }
            JOptionPane.showMessageDialog(this, "The system has loaded ATP List. ", "Details ", JOptionPane.INFORMATION_MESSAGE);
            new FrmDetailsATPLists(null, true, atplist).setVisible(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmSearchTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "The system cannot load ATP List.", "Details ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelATPLists;
    private javax.swing.JTable tblATPLists;
    private javax.swing.JTextField txtATPList;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        btnDetails.setVisible(false);
        tblATPLists.setModel(new TableModelATPList(new ArrayList<>()));
    }

    private void prepareTable(List<ATPList> newATPLists) {
        tblATPLists.setModel(new TableModelATPList(newATPLists));
    }
}
