/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.player;

import controller.Communication;
import domain.ATPList;
import domain.Player;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import validator.IValidator;
import validator.ValidatorException;
import validator.components.RegularValidator;

/**
 *
 * @author DELL
 */
public class FrmDetailsPlayer extends javax.swing.JDialog {
    
    Player player;
    Player x;
    List<ATPList> atpList;
    IValidator validator = new RegularValidator();

    /**
     * Creates new form FrmDetailsPlayer
     */
    public FrmDetailsPlayer(java.awt.Frame parent, boolean modal, Player player) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.player = player;
        prepareForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        txtPoints = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblATPList = new javax.swing.JLabel();
        btnAllowChanges = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        cmbATPList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFirstName.setText("First name:");

        lblLastName.setText("Last name:");

        lblBirthday.setText("Birthday:");

        lblState.setText("State:");

        lblPoints.setText("Points:");

        lblHeight.setText("Height:");

        lblWeight.setText("Weight:");

        lblATPList.setText("ATPList:");

        btnAllowChanges.setText("Allow changes");
        btnAllowChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowChangesActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnViewAll.setText("View All Players");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnAllowChanges)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(btnDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(lblBirthday)
                            .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblATPList)
                            .addComponent(lblWeight)
                            .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtState, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(cmbATPList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirthday)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoints)
                    .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblATPList)
                    .addComponent(cmbATPList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAllowChanges)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnViewAll))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllowChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowChangesActionPerformed
        btnUpdate.setEnabled(true);
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtHeight.setEnabled(true);
        txtWeight.setEnabled(true);
        txtPoints.setEnabled(true);
        txtBirthday.setEnabled(true);
        txtState.setEnabled(true);
        cmbATPList.setEnabled(true);
    }//GEN-LAST:event_btnAllowChangesActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel updating player: " + player.getFirstName() + " " + player.getLastName());
        if(option == 0) {
            this.dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
                validator.validatePlayer(txtFirstName.getText().trim(), txtLastName.getText().trim(), txtState.getText().trim(), txtPoints.getText(), txtHeight.getText(), txtWeight.getText());
            } catch(ValidatorException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        LocalDate birthday;
            try {
                LocalDate.parse(txtBirthday.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Please insert date in format YYYY/MM/DD", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        birthday = LocalDate.parse(txtBirthday.getText());
        if(birthday.isAfter(LocalDate.now(ZoneId.systemDefault()))) {
            JOptionPane.showMessageDialog(this, "Please insert date that isn't after today's date!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String state = txtState.getText().trim();
        Integer points = Integer.parseInt(txtPoints.getText());
        Double height = Double.parseDouble(txtHeight.getText());
        Double weight = Double.parseDouble(txtWeight.getText());
        ATPList atplist = (ATPList) cmbATPList.getSelectedItem();
        
        if(birthday.isAfter(LocalDate.now(ZoneId.systemDefault()))) {
                JOptionPane.showMessageDialog(this, "Please insert date that isn't after today's date!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to update player: " + player.getFirstName() + " " + player.getLastName());
        if(option == 0) {
            try {
                player.setFirstName(firstName);
                player.setLastName(lastName);
                player.setBirthday(birthday);
                player.setState(state);
                player.setPoints(points);
                player.setHeight(height);
                player.setWeight(weight);
                player.setAtpList(atplist);
                x = Communication.getInstance().updatePlayer(player);
                JOptionPane.showMessageDialog(this, "The system has memorized player. ", "Update", JOptionPane.INFORMATION_MESSAGE);
                
                btnUpdate.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtLastName.setEnabled(false);
                txtHeight.setEnabled(false);
                txtWeight.setEnabled(false);
                txtPoints.setEnabled(false);
                txtBirthday.setEnabled(false);
                txtState.setEnabled(false);
                cmbATPList.setEnabled(false);
                btnViewAll.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmDetailsPlayer.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "The system cannot memorize player. ", "Update", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete player: " + player.getFirstName() + " " + player.getLastName() + " ?" );
        if(option == 0) {
            try {
                Communication.getInstance().deletePlayer(player);
                JOptionPane.showMessageDialog(this, "The system has deleted player.", "Delete", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FrmDetailsPlayer.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "The system cannot delete player.", "Delete", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        this.dispose();
        new FrmViewPlayers(null, true).setVisible(true);
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllowChanges;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JComboBox<ATPList> cmbATPList;
    private javax.swing.JLabel lblATPList;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPoints;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        btnUpdate.setEnabled(false);
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtHeight.setEnabled(false);
        txtWeight.setEnabled(false);
        txtPoints.setEnabled(false);
        txtBirthday.setEnabled(false);
        txtState.setEnabled(false);
        cmbATPList.setEnabled(false);
        btnViewAll.setVisible(false);
        
        txtFirstName.setText(player.getFirstName());
        txtLastName.setText(player.getLastName());
        txtBirthday.setText(String.valueOf(player.getBirthday()));
        txtState.setText(player.getState());
        txtPoints.setText(String.valueOf(player.getPoints()));
        txtHeight.setText(String.valueOf(player.getHeight()));
        txtWeight.setText(String.valueOf(player.getWeight()));
        
        try {
            atpList = Communication.getInstance().getAllATPLists();
            for (ATPList a : atpList) {
                cmbATPList.addItem(a);
            }
            cmbATPList.setSelectedItem(player.getAtpList());
        } catch (Exception ex) {
            System.out.println("asjfisadafaafaafa");
            Logger.getLogger(FrmDetailsPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
